apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: climacast
spec:
  selector:
    app: ai-service
  ports:
    - port: 80
      targetPort: 8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: climacast
spec:
  selector:
    matchLabels:
      app: ai-service
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ai-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8070"
    spec:
      containers:
        - name: ai-service
          image: climacast/ai-service:${IMAGE_TAG}
          imagePullPolicy: Never
          ports:
            - containerPort: 8070
          env:
            - name: APPLICATION_PROFILE
              value: prod