apiVersion: v1
kind: Service
metadata:
  name: batch-server
  namespace: climacast
spec:
  selector:
    app: batch-server
  clusterIP: None
  ports:
    - port: 8999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-server
  namespace: climacast
spec:
  selector:
    matchLabels:
      app: batch-server
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: batch-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8999"
    spec:
      containers:
        - name: batch-server
          image: climacast/batch-server:${IMAGE_TAG}
          imagePullPolicy: Never
          ports:
            - containerPort: 8999
          env:
            - name: APPLICATION_PROFILE
              value: prod
            - name: TZ
              value: Asia/Seoul