apiVersion: v1
kind: Service
metadata:
  name: batch-server
spec:
  selector:
    app: batch-server
  clusterIP: None
  ports:
    - port: 8999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-server-deployment
spec:
  selector:
    matchLabels:
      app: batch-server
  replicas: 3
  template:
    metadata:
      labels:
        app: batch-server
    spec:
      containers:
        - name: batch-server
          image: climacast/batch-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8999
          env:
            - name: APPLICATION_PROFILE
              value: prod
            - name: TZ
              value: Asia/Seoul