apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchFields:
                  - key: metadata.name
                    operator: In
                    values:
                      - minikube
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: discovery.type
              value: single-node
#            - name: discovery.seed_hosts
#              value: elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch
#            - name: cluster.initial_master_nodes
#              value: elasticsearch-0,elasticsearch-1,elasticsearch-2
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.enrollment.enabled
              value: "false"
            - name: bootstrap.memory_lock
              value: "true"
          volumeMounts:
            - name: es-data
              mountPath: /var/data/elasticsearch
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        selector:
          matchLabels:
            app: elasticsearch
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi