apiVersion: v1
kind: Service
metadata:
  name: mysql-source
spec:
  selector:
    app: mysql-source
  ports:
    - port: 3307
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica
spec:
  selector:
    app: mysql-replica
  ports:
    - port: 3308
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-batch
spec:
  selector:
    app: mysql-batch
  ports:
    - port: 3309
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-source
spec:
  serviceName: mysql-source
  replicas: 1
  selector:
    matchLabels:
      app: mysql-source
  template:
    metadata:
      labels:
        app: mysql-source
    spec:
      containers:
        - name: mysql-source
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
              readOnly: true
            - name: mysql-source-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-source-configmap
  volumeClaimTemplates:
    - metadata:
        name: mysql-source-data
      spec:
        selector:
          matchLabels:
            app: mysql-source
        accessModes:
          - ReadWriteOnce
        storageClassName: mysql-storage
        resources:
          requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica
spec:
  serviceName: mysql-replica
  replicas: 2
  selector:
    matchLabels:
      app: mysql-replica
  template:
    metadata:
      labels:
        app: mysql-replica
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mysql-replica
                      - mysql-source
      containers:
        - name: mysql-replica
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
              readOnly: true
            - name: mysql-replica-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-replica-configmap
  volumeClaimTemplates:
    - metadata:
        name: mysql-replica-data
      spec:
        selector:
          matchLabels:
            app: mysql-replica
        accessModes:
          - ReadWriteOnce
        storageClassName: mysql-storage
        resources:
          requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-batch
spec:
  serviceName: mysql-batch
  replicas: 1
  selector:
    matchLabels:
      app: mysql-batch
  template:
    metadata:
      labels:
        app: mysql-batch
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mysql-batch
      containers:
        - name: mysql-batch
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-batch-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-batch-data
      spec:
        selector:
          matchLabels:
            app: mysql-batch
        accessModes:
          - ReadWriteOnce
        storageClassName: mysql-storage
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-source-configmap
data:
  my.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog-format=ROW
    relay-log=mysql-relay-bin
    skip-name-resolve
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-replica-configmap
data:
  my.cnf: |
    [mysqld]
    server-id=2
    log-bin=mysql-bin
    binlog-format=ROW
    relay-log=mysql-relay-bin
    skip-name-resolve
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci