apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: database
  labels:
    app: redis
spec:
  selector:
    app: redis
  clusterIP: None
  ports:
    - port: 6379
      name: client
    - port: 16379
      name: gossip
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: database
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - redis
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - redis-server
            - /etc/redis.conf
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis.conf
              subPathExpr: "$(HOSTNAME).conf"
            - name: redis-volume
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: redis-configmap
  volumeClaimTemplates:
    - metadata:
        name: redis-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: redis-storage
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: database
data:
  redis-0.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 3000
    appendonly yes
  redis-1.conf: |
    port 6380
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 3000
    appendonly yes
  redis-2.conf: |
    port 6381
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 3000
    appendonly yes