services:
  source:
    container_name: mysql-source
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3307:3306
    volumes:
      - source-data:/var/lib/mysql
      - source-logs:/var/lib/mysql-files
      - ./my-source.cnf:/etc/mysql/my.cnf
    restart: always
    networks:
      - mysql-network
  replica:
    container_name: mysql-replica
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3308:3306
    volumes:
      - replica-data:/var/lib/mysql
      - replica-logs:/var/lib/mysql-files
      - ./my-replica.cnf:/etc/mysql/my.cnf
    depends_on:
      - source
    restart: always
    networks:
      - mysql-network

networks:
  mysql-network:

volumes:
  source-data:
  source-logs:
  replica-data:
  replica-logs: