services:
  local:
    container_name: mysql-local
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_USER}
    ports:
      - 3306:3306
    volumes:
      - local-data:/var/lib/mysql
    restart: always
    networks:
      - mysql-network
  source:
    container_name: mysql-source
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3307:3306
    volumes:
      - source-data:/var/lib/mysql
      - source-logs:/var/lib/mysql-files
      - ./mysql/my-source.cnf:/etc/mysql/my.cnf
    restart: always
    networks:
      - mysql-network
  replica:
    container_name: mysql-replica
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3308:3306
    volumes:
      - replica-data:/var/lib/mysql
      - replica-logs:/var/lib/mysql-files
      - ./mysql/my-replica.cnf:/etc/mysql/my.cnf
    depends_on:
      - source
    restart: always
    networks:
      - mysql-network

networks:
  mysql-network:

volumes:
  local-data:
  source-data:
  source-logs:
  replica-data:
  replica-logs: