services:
  mysql-source:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - 3307:3306
    volumes:
      - source-data:/var/lib/mysql
      - source-logs:/var/lib/mysql-files
      - ./mysql/my-source.cnf:/etc/mysql/my.cnf
    networks:
      - mysql-network

  mysql-replica:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - 3308:3306
    volumes:
      - replica-data:/var/lib/mysql
      - replica-logs:/var/lib/mysql-files
      - ./mysql/my-replica.cnf:/etc/mysql/my.cnf
    depends_on:
      - mysql-source
    networks:
      - mysql-network

  mysql-batch:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - 3309:3306
    volumes:
      - batch-data:/var/lib/mysql
    networks:
      - mysql-network

networks:
  mysql-network:

volumes:
  source-data:
  source-logs:
  replica-data:
  replica-logs:
  batch-data: