services:
  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: config-server/Dockerfile
    image: climacast/config-server:latest
    ports:
      - 8888:8888
    environment:
      - spring.cloud.config.server.git.host-key=${CONFIG_SERVER_HOST_KEY}
      - spring.cloud.config.server.git.private-key=${CONFIG_SERVER_PRIVATE_KEY}
    restart: always
    networks:
      - climacast-network

  eureka-server:
    container_name: eureka-server
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    image: climacast/eureka-server:latest
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES=dev
    depends_on:
      - config-server
    restart: always
    networks:
      - climacast-network

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: climacast/api-gateway:latest
    ports:
      - 8000:8000
    environment:
      - SPRING_PROFILES=dev
    depends_on:
      - config-server
      - eureka-server
    restart: always
    networks:
      - climacast-network

  batch-server:
    container_name: batch-server
    build:
      context: .
      dockerfile: batch-server/Dockerfile
    image: climacast/batch-server:latest
    ports:
      - 8999:8999
    environment:
      - SPRING_PROFILES=dev
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
      - mysql-batch
      - mysql-source
      - mysql-replica
    restart: always
    networks:
      - climacast-network

  mysql-batch:
    container_name: mysql-batch
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - batch-data:/var/lib/mysql
    networks:
      - climacast-network

  mysql-source:
    container_name: mysql-source
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3307:3306
    volumes:
      - source-data:/var/lib/mysql
      - source-logs:/var/lib/mysql-files
      - ./mysql/my-source.cnf:/etc/mysql/my.cnf
    networks:
      - climacast-network

  mysql-replica:
    container_name: mysql-replica
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3308:3306
    volumes:
      - replica-data:/var/lib/mysql
      - replica-logs:/var/lib/mysql-files
      - ./mysql/my-replica.cnf:/etc/mysql/my.cnf
    depends_on:
      - mysql-source
    networks:
      - climacast-network

networks:
  climacast-network:

volumes:
  batch-data:
  source-data:
  source-logs:
  replica-data:
  replica-logs: