services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    image: ${ECR_REGISTRY}/climacast:config-server-${GIT_COMMIT_HASH}
    container_name: config-server
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - climacast-network

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    image: ${ECR_REGISTRY}/climacast:eureka-server-${GIT_COMMIT_HASH}
    container_name: eureka-server
    ports:
      - 18761:8761
    environment:
      APPLICATION_PROFILE: prod
    depends_on:
      - config-server
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8761/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: ${ECR_REGISTRY}/climacast:api-gateway-${GIT_COMMIT_HASH}
    container_name: api-gateway
    ports:
      - 18000:8000
    environment:
      APPLICATION_PROFILE: prod
    depends_on:
      - config-server
      - eureka-server
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8000/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

  batch-server:
    build:
      context: .
      dockerfile: batch-server/Dockerfile
    image: ${ECR_REGISTRY}/climacast:batch-server-${GIT_COMMIT_HASH}

  subscription-service:
    build:
      context: .
      dockerfile: subscription-service/Dockerfile
    image: ${ECR_REGISTRY}/climacast:subscription-service-${GIT_COMMIT_HASH}

  batch-server-blue:
    image: ${ECR_REGISTRY}/climacast:batch-server-${GIT_COMMIT_HASH}
    ports:
      - "18998-18999:8999"
    scale: 2
    environment:
      APPLICATION_PROFILE: prod
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
      - mysql-source
      - mysql-replica
      - mysql-batch
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8999/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

  batch-server-green:
    image: ${ECR_REGISTRY}/climacast:batch-server-${GIT_COMMIT_HASH}
    ports:
      - "28998-28999:8999"
    scale: 2
    environment:
      APPLICATION_PROFILE: prod
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
      - mysql-source
      - mysql-replica
      - mysql-batch
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8999/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

  subscription-service-blue:
    image: ${ECR_REGISTRY}/climacast:subscription-service-${GIT_COMMIT_HASH}
    ports:
      - "18090-18091:8090"
    scale: 2
    environment:
      APPLICATION_PROFILE: prod
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
      - mysql-source
      - mysql-replica
      - elasticsearch
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

  subscription-service-green:
    image: ${ECR_REGISTRY}/climacast:subscription-service-${GIT_COMMIT_HASH}
    ports:
      - "28090-28091:8090"
    scale: 2
    environment:
      APPLICATION_PROFILE: prod
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
      - mysql-source
      - mysql-replica
      - elasticsearch
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://kafka-1:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - 9092:9092
      - 19092:19092
    depends_on:
      - zookeeper
    networks:
      - climacast-network

  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka-2:19093,EXTERNAL://kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19093,EXTERNAL://kafka-2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - 9093:9093
      - 19093:19093
    depends_on:
      - zookeeper
    networks:
      - climacast-network

  kafka-3:
    image: bitnami/kafka:latest
    container_name: kafka-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka-3:19094,EXTERNAL://kafka-3:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:19094,EXTERNAL://kafka-3:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - 9094:9094
      - 19094:19094
    depends_on:
      - zookeeper
    networks:
      - climacast-network

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - 12181:2181
    networks:
      - climacast-network

  mysql-source:
    image: mysql:latest
    container_name: mysql-source
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    volumes:
      - source-data:/var/lib/mysql
      - source-logs:/var/lib/mysql-files
      - ./mysql/my-source.cnf:/etc/mysql/my.cnf
    networks:
      - climacast-network

  mysql-replica:
    image: mysql:latest
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - 3308:3306
    volumes:
      - replica-data:/var/lib/mysql
      - replica-logs:/var/lib/mysql-files
      - ./mysql/my-replica.cnf:/etc/mysql/my.cnf
    depends_on:
      - mysql-source
    networks:
      - climacast-network

  mysql-batch:
    image: mysql:latest
    container_name: mysql-batch
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - 3309:3306
    volumes:
      - batch-data:/var/lib/mysql
    networks:
      - climacast-network

  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    ports:
      - 19200:9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - climacast-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    networks:
      - climacast-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 16379:6379
    restart: always
    networks:
      - climacast-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 19090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - climacast-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 13000:3000
    networks:
      - climacast-network

networks:
  climacast-network:

volumes:
  source-data:
  source-logs:
  replica-data:
  replica-logs:
  batch-data: