services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    image: climacast/config-server:latest
    container_name: config-server
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - climacast-network

  batch-server:
    build:
      context: .
      dockerfile: batch-server/Dockerfile
    image: climacast/batch-server:${IMAGE_TAG}
    ports:
      - 8999:8999
    environment:
      APPLICATION_PROFILE: dev
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8999/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

  subscription-service:
    build:
      context: .
      dockerfile: subscription-service/Dockerfile
    image: climacast/subscription-service:${IMAGE_TAG}
    ports:
      - 8090:8090
    environment:
      APPLICATION_PROFILE: dev
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

  ai-service:
    build:
      dockerfile: ai-service/Dockerfile
      context: .
    image: climacast/ai-service:${IMAGE_TAG}
    ports:
      - 8070:8070
    environment:
      APPLICATION_PROFILE: dev
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8070/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - climacast-network

networks:
  climacast-network: