services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - 3306:3306
    networks:
      - climacast-network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - climacast-network

networks:
  climacast-network: