scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:18761' ]
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:18000' ]
  - job_name: 'batch-server-blue'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:18998', 'host.docker.internal:18999' ]
  - job_name: 'batch-server-green'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:28998', 'host.docker.internal:28999' ]
  - job_name: 'subscription-service-blue'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:18090', 'host.docker.internal:18091' ]
  - job_name: 'subscription-service-green'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:28090', 'host.docker.internal:28091' ]