server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka