package com.climacast.subscription_service.model.repository

import com.climacast.subscription_service.model.document.HistoryWeather
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository

interface HistoryWeatherSearchRepository: ElasticsearchRepository<HistoryWeather, String>