server:
  port: 8999

spring:
  application:
    name: batch-server
  cloud:
    config:
      enabled: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  datasource:
    batch:
      jdbcUrl: ${mysql.batch}
      username: ${mysql.username}
      password: ${mysql.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: batch-db-pool
      maximum-pool-size: 10
      minimum-idle: 5
    weather:
      source:
        hikari:
          jdbcUrl: ${mysql.weather.source}
          username: ${mysql.username}
          password: ${mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          pool-name: weather-source-db-pool
          maximum-pool-size: 10
          minimum-idle: 5
      replica:
        hikari:
          jdbcUrl: ${mysql.weather.replica}
          username: ${mysql.username}
          password: ${mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          pool-name: weather-replica-db-pool
          maximum-pool-size: 20
          minimum-idle: 10

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        jdbc: debug