server:
  port: 8999

spring:
  application:
    name: batch-server
  cloud:
    config:
      enabled: false
  datasource:
    url: ${db.mysql.batch}
    username: ${db.mysql.username}
    password: ${db.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka