server:
  port: 8999

spring:
  application:
    name: batch-server
  cloud:
    config:
      enabled: false
  batch:
    jdbc:
      initialize-schema: never
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  datasource:
    batch:
      hikari:
        jdbc-url: ${db.mysql.batch}
        username: ${db.mysql.username}
        password: ${db.mysql.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    weather:
      hikari:
        source:
          jdbc-url: ${db.mysql.weather.source}
          username: ${db.mysql.username}
          password: ${db.mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          maximum-pool-size: 10
          minimum-idle: 5
          pool-name: MasterHikariCP
        replica:
          jdbc-url: ${db.mysql.weather.replica}
          username: ${db.mysql.username}
          password: ${db.mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          maximum-pool-size: 20
          minimum-idle: 10
          pool-name: SlaveHikariCP

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        jdbc: debug