apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      name: external
    - port: 19092
      targetPort: 19092
      name: internal
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 2181
      targetPort: 2181