apiVersion: v1
kind: Service
metadata:
  name: mysql-source
spec:
  selector:
    app: mysql-source
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica
spec:
  selector:
    app: mysql-replica
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-batch
spec:
  selector:
    app: mysql-batch
  ports:
    - protocol: TCP
      port: 3309
      targetPort: 3306
  type: ClusterIP