server:
  port: 8090

spring:
  application:
    name: subscription-service
  cloud:
    config:
      enabled: false
  threads:
    virtual:
      enabled: true
  mail:
    host: ${gmail.host}
    port: ${gmail.port}
    username: ${gmail.username}
    password: ${gmail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

redis:
  host: localhost
  port: 6379

logging:
  level:
    org:
      springframework:
        scheduling: debug