server:
  port: 8090

spring:
  application:
    name: subscription-service
  cloud:
    config:
      enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  datasource:
    source:
      hikari:
        jdbc-url: ${mysql.subscription.local}
        username: ${mysql.username}
        password: ${mysql.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: subscription-source-db-pool
        maximum-pool-size: 10
        minimum-idle: 5
    replica:
      hikari:
        jdbc-url: ${mysql.subscription.local}
        username: ${mysql.username}
        password: ${mysql.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: subscription-replica-db-pool
        maximum-pool-size: 20
        minimum-idle: 10
  mail:
    host: ${gmail.host}
    port: ${gmail.port}
    username: ${gmail.username}
    password: ${gmail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

redis:
  host: localhost
  port: 6379

logging:
  level:
    org:
      springframework:
        scheduling: debug