server:
  port: 8070

spring:
  application:
    name: ai-service
  cloud:
    config:
      enabled: false
  ai:
    openai:
      base-url: ${groq.base-url}
      api-key: ${groq.api-key}
      chat:
        options:
          model: ${groq.model}
    ollama:
      chat:
        model: llama3.2
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 3000
      timeout: 3000

logging:
  level:
    org:
      springframework:
        scheduling: debug

app:
  kafka:
    num-partitions: 1
    replication-factor: 1