server:
  port: 8070

spring:
  application:
    name: ai-service
  cloud:
    config:
      enabled: false
  ai:
    openai:
      api-key: ${openai.api-key}
      chat:
        options:
          model: gpt-3.5-turbo
    ollama:
      chat:
        model: llama3.2

logging:
  level:
    org:
      springframework:
        scheduling: debug

redis:
  host: localhost
  port: 6379