apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1-deployment
spec:
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka-1
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 19092
          env:
            - name: KAFKA_CFG_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CFG_LISTENERS
              value: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-1:19092,EXTERNAL://kafka-1:9092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2-deployment
spec:
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
        - name: kafka-2
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9093
            - containerPort: 19093
          env:
            - name: KAFKA_CFG_BROKER_ID
              value: "2"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CFG_LISTENERS
              value: INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-2:19093,EXTERNAL://kafka-2:9093
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-3-deployment
spec:
  selector:
    matchLabels:
      app: kafka-3
  template:
    metadata:
      labels:
        app: kafka-3
    spec:
      containers:
        - name: kafka-3
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9094
            - containerPort: 19094
          env:
            - name: KAFKA_CFG_BROKER_ID
              value: "3"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CFG_LISTENERS
              value: INTERNAL://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-3:19094,EXTERNAL://kafka-3:9094
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181