apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-source-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-replica-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-batch-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-source-pv
  labels:
    app: mysql-source
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-source-storage
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mysql/source
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube-m02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv-0
  labels:
    app: mysql-replica
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-replica-storage
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mysql/replica_0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube-m03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv-1
  labels:
    app: mysql-replica
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-replica-storage
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mysql/replica_1
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube-m04
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-batch-pv
  labels:
    app: mysql-batch
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-batch-storage
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mysql/batch
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube-m02