apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage
  labels:
    app: mysql
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-source-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: /mysql/mysql_data/source
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv-0
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: /mysql/mysql_data/replica
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv-1
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: /mysql/mysql_data/replica
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv-2
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: /mysql/mysql_data/replica
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-batch-pv-0
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: /mysql/mysql_data/batch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-batch-pv-1
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: /mysql/mysql_data/batch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-batch-pv-2
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: /mysql/mysql_data/batch