apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-weather-source-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-weather-replica-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-subscription-source-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-subscription-replica-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-batch-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-weather-source-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-weather-source-storage
  claimRef:
    name: mysql-weather-source-volume
    namespace: database
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql/mysql-weather-source
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-weather-replica-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-weather-replica-storage
  claimRef:
    name: mysql-weather-replica-volume
    namespace: database
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql/mysql-weather-replica-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-weather-replica-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-weather-replica-storage
  claimRef:
    name: mysql-weather-replica-volume
    namespace: database
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql/mysql-weather-replica-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-subscription-source-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-subscription-source-storage
  claimRef:
    name: mysql-subscription-source-volume
    namespace: database
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql/mysql-subscription-source
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-subscription-replica-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-subscription-replica-storage
  claimRef:
    name: mysql-subscription-replica-volume
    namespace: database
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql/mysql-subscription-replica-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-subscription-replica-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-subscription-replica-storage
  claimRef:
    name: mysql-subscription-replica-volume
    namespace: database
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql/mysql-subscription-replica-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-batch-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-batch-storage
  claimRef:
    name: mysql-batch-volume
    namespace: database
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql/mysql-batch