apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-source-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mysql/mysql_data/source
  claimRef:
    name: mysql-source-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mysql/mysql_data/replica
  claimRef:
    name: mysql-replica-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-batch-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mysql/mysql_data/batch
  claimRef:
    name: mysql-batch-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-replica-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-batch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi