apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage
  labels:
    app: mysql
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-source-pv
  labels:
    app: mysql-source
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mysql/source
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube-m02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv-0
  labels:
    app: mysql-replica
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mysql/replica_0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube-m03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv-1
  labels:
    app: mysql-replica
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mysql/replica_1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube-m04
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-batch-pv
  labels:
    app: mysql-batch
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mysql/batch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube-m02