apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ollama-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: ai
spec:
  storageClassName: ollama-storage
  volumeName: ollama-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ollama-storage
  hostPath:
    path: /data/ollama
  persistentVolumeReclaimPolicy: Retain