apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: weather-image-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-image-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: weather-image-storage
  hostPath:
    path: /tmp/weather-image
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-image-pvc
  namespace: climacast
spec:
  storageClassName: weather-image-storage
  volumeName: weather-image-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi