apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: weather-image-storage
  labels:
    app: weather
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-image-pv
  labels:
    app: weather
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: weather-image-storage
  hostPath:
    path: /mnt/weather-image
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-image-pvc
  labels:
    app: weather
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: weather-image-storage
  resources:
    requests:
      storage: 1Gi