apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: messaging
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  clusterIP: None
  ports:
    - port: 9092
      name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: monitoring
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - port: 10000
      targetPort: 8080
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: messaging
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      restartPolicy: Always
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(MY_POD_NAME).kafka.messaging.svc.cluster.local:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zk-0.zk-hs.messaging.svc.cluster.local:2181,zk-1.zk-hs.messaging.svc.cluster.local:2181,zk-2.zk-hs.messaging.svc.cluster.local:2181
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
          command:
            - sh
            - -c
            - |
              export KAFKA_BROKER_ID=$(echo ${MY_POD_NAME} | awk -F'-' '{print $NF}')
              echo "Setting KAFKA_BROKER_ID to $KAFKA_BROKER_ID"
              export KAFKA_BROKER_ID
              /usr/bin/start-kafka.sh
          volumeMounts:
            - name: kafka-volume
              mountPath: /var/lib/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: monitoring
  labels:
    app: kafka-ui
spec:
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: climacast-kafka-cluster
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-0.kafka.messaging.svc.cluster.local:9092,kafka-1.kafka.messaging.svc.cluster.local:9092,kafka-2.kafka.messaging.svc.cluster.local:9092
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: zk-0.zk-hs.messaging.svc.cluster.local:2181