apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: messaging
  labels:
    app: zk
spec:
  selector:
    app: zk
  clusterIP: None
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  namespace: messaging
  labels:
    app: zk
spec:
  selector:
    app: zk
  ports:
    - port: 2181
      name: client
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: messaging
  labels:
    app: zk
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zk
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - zk
      containers:
        - name: kubernetes-zookeeper
          image: confluentinc/cp-zookeeper:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
              cpu: "0.5"
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZOOKEEPER_SERVERS
              value: zk-0.zk-hs.messaging.svc.cluster.local:2888:3888;zk-1.zk-hs.messaging.svc.cluster.local:2888:3888;zk-2.zk-hs.messaging.svc.cluster.local:2888:3888
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "3"
          command:
            - sh
            - -c
            - |
              export ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-} + 1))
              /etc/confluent/docker/run
          volumeMounts:
            - name: zk-volume
              mountPath: /var/lib/zookeeper/data
      securityContext:
        runAsUser: 0
        fsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: zk-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi