server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yunhozz/config-repository.git
          default-label: master
          search-paths: climacast/
          clone-on-start: true
          ignore-local-ssh-settings: true
          strict-host-key-checking: false
          host-key-algorithm: ecdsa-sha2-nistp256
          host-key: ${config.server.host-key}
          private-key: ${config.server.private-key}
        encrypt:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true