name: Deploy to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Load Properties and Environments from Secrets and Process
        run: |
          mkdir -p ./global/src/main/resources

          touch ./global/src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./global/src/main/resources/application.properties

          touch ./config-server/src/main/resources/application-key.yml
          echo "${{ secrets.APPLICATION_KEY_YML }}" | base64 -d > ./config-server/src/main/resources/application-key.yml

          echo "${{ secrets.ENV }}" > .env

      - name: Build and push Docker images to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GIT_COMMIT_HASH: ${{ github.sha }}
        run: |
          echo "GIT_COMMIT_HASH=${GIT_COMMIT_HASH}" >> .env
          SERVICES=("config-server" "eureka-server" "api-gateway" "batch-server" "subscription-service")

          for SERVICE in ${SERVICES[@]}; do
            IMAGE_TAG="${SERVICE}-${GIT_COMMIT_HASH}"
            echo "Building image for $SERVICE with tag $IMAGE_TAG"
          
            docker compose build $SERVICE
            docker image ls
            docker tag climacast/$SERVICE:${GIT_COMMIT_HASH} $ECR_REGISTRY/climacast:$IMAGE_TAG
            docker push $ECR_REGISTRY/climacast:$IMAGE_TAG

            echo "${SERVICE}-image=${ECR_REGISTRY}/climacast:$IMAGE_TAG" >> $GITHUB_ENV
          done

      - name: Setup SSH key for EC2
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-3-39-252-185.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Copy Files to EC2
        run: |
          scp -i ~/.ssh/id_rsa ./docker-compose.yml ubuntu@ec2-3-39-252-185.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/
          scp -i ~/.ssh/id_rsa -r ./nginx ubuntu@ec2-3-39-252-185.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/
          scp -i ~/.ssh/id_rsa ./deploy.sh ubuntu@ec2-3-39-252-185.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/
          scp -i ~/.ssh/id_rsa ./.env ubuntu@ec2-3-39-252-185.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/
          scp -i ~/.ssh/id_rsa ./prometheus-dev.yml ubuntu@ec2-3-39-252-185.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-3-39-252-185.ap-northeast-2.compute.amazonaws.com << 'EOF'
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $ECR_REGISTRY

          for SERVICE in $(docker compose config --services); do
            IMAGE_TAG="${SERVICE}-${GIT_COMMIT_HASH}"
            docker pull ${ECR_REGISTRY}/climacast:$IMAGE_TAG
          done

          cd /home/ubuntu
          chmod +x deploy.sh
          ./deploy.sh
          EOF