name: Develop to Master PR Test

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Load Properties and Environments from secrets and process
        run: |
          mkdir -p ./global/src/main/resources
          mkdir -p ./nginx/conf.d
          
          touch ./global/src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./global/src/main/resources/application.properties
          
          touch ./config-server/src/main/resources/application-key.yml
          echo "${{ secrets.APPLICATION_KEY_YML }}" | base64 -d > ./config-server/src/main/resources/application-key.yml
          
          echo "${{ secrets.ENV }}" > .env
          
          echo 'user nginx;' > nginx/nginx.conf
          echo 'worker_processes auto;' >> nginx/nginx.conf
          echo 'error_log /var/log/nginx/error.log warn;' >> nginx/nginx.conf
          echo 'pid /var/run/nginx.pid;' >> nginx/nginx.conf
          echo 'events { worker_connections 1024; }' >> nginx/nginx.conf
          echo 'http { server { listen 80; server_name localhost; location / { root /usr/share/nginx/html; } } }' >> nginx/nginx.conf

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose-dev.yml --env-file .env up -d
          docker compose -f docker-compose-dev.yml ps
          sleep 10

      - name: Wait for services to be ready
        run: |
          declare -A SERVICES=(
            ["config-server"]="http://127.0.0.1:8888/actuator/health"
            ["eureka-server"]="http://127.0.0.1:18761/actuator/health"
            ["api-gateway"]="http://127.0.0.1:18000/actuator/health"
            ["batch-server-blue"]="http://127.0.0.1:18999/actuator/health"
            ["batch-server-green"]="http://127.0.0.1:28999/actuator/health"
            ["subscription-service-blue"]="http://127.0.0.1:18090/actuator/health"
            ["subscription-service-green"]="http://127.0.0.1:28090/actuator/health"
          )
          
          for i in {1..10}; do
            ALL_SERVICES_READY=true
          
            for SERVICE in "${!SERVICES[@]}"; do
              URL=${SERVICES[$SERVICE]}
              HTTP_STATUS=$(curl -v -o /dev/null -s -w "%{http_code}" $URL)
          
              if [[ "$HTTP_STATUS" != "200" ]]; then
                echo "$SERVICE is not ready yet (HTTP $HTTP_STATUS)..."
                ALL_SERVICES_READY=false
              else
                echo "$SERVICE is ready (HTTP $HTTP_STATUS)."
              fi
            done
          
            if [[ "$ALL_SERVICES_READY" == true ]]; then
              echo "All services are healthy!"
              break
            fi
          
            echo "Waiting for all services to be ready..."
            sleep 6
          done